name: secure checkout

description: 'secure checkout'

inputs:
  repository:
    description: '...'
    type: string
    required: true

  ref:
    description: '...'
    type: string
    required: true

  path:
    description: 'path'
    type: string
    required: true

  token:
    description: "Token used to fetch the repository."
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout the builder
      # TODO: use a secure builder checkout.
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      with:
        fetch-depth: 1
        persist-credentials: false
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}