name: 'Generate Attestations'
description: 'Generates in-toto attestations based on a builds SLSA outputs layout and other trusted metadata inputs'
inputs:
  slsa-outputs-file:
    description: 'A JSON file describing the SLSA output layout with attestation filename keys and the generated subjects (and digests)'
    required: true
  tool-inputs:
    description: 'The SLSA tool inputs used for the tool run.'
    required: true
  tool-uri:
    description: 'The tool URI'
    required: true
  tool-path:
    description: 'The path to the tool, relative to the tool repository'
    required: true
  output-folder:
    description: 'Output folder to place attestations'
    required: false
    default: 'outputs'
outputs:
  output-folder:
    description: 'Output folder where attestations were placed'
runs:
  using: 'node16'
  main: 'dist/index.js'
