name: pre-submit env var

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  debug:  
    runs-on: ubuntu-latest
    steps:
      env:
        GITHUB_WORKFLOW_REF_CONTEXT: ${{ github.workflow_ref }}
        GITHUB_WORKFLOW_SHA_CONTEXT: ${{ github.workflow_sha }}
      - run: |
          echo "Github repository: ${GITHUB_REPOSITORY}"
          echo "Github workflow: ${GITHUB_WORKFLOW}"
          echo "Github workflow sha: ${GITHUB_WORKFLOW_SHA}"
          echo "Github workflow sha context: ${GITHUB_WORKFLOW_SHA_CONTEXT}"
          echo "Github workflow ref: ${GITHUB_WORKFLOW_REF}"
          echo "Github workflow ref context: ${GITHUB_WORKFLOW_REF_CONTEXT}"
          
