name: pre-submit actions

on:
  workflow_dispatch:

permissions: read-all

jobs:
  
  setup-token:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - id: setup
        uses: ./actions/setup-token
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-private-repository: true
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./actions/build-artifacts-composite"
          slsa-workflow-inputs: '{"name1":"value1","name2":"value2","private-repository":true}'

      - env:
          SLSA_TOKEN: ${{ steps.setup.outputs.slsa-token }}
          CONTEXT: ${{ toJson(github) }}
        run: ./.github/workflows/scripts/pre-submit.actions/setup-token.sh