name: pre-submit actions

on:
  workflow_dispatch:

permissions: read-all

jobs:
  
  setup-token:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - id: setup
        uses: ./actions/setup-token
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-private-repository: true
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./actions/build-artifacts-composite"
          slsa-workflow-inputs: '{"name1":"value1","name2":"value2","private-repository":true}'

      - env:
          SLSA_TOKEN: ${{ steps.setup.outputs.slsa-token }}
          CONTEXT: ${{ github.context }}
        run: |
          set -euo pipefail

          # NOTE: this is a pre-submit, so the signature is not generated and there is
          # just a place holder for it.
          echo "SLSA_TOKEN: $SLSA_TOKEN"
          [[ "$SLSA_TOKEN" != "" ]]

          b64_token="$(echo -n $SLSA_TOKEN | cut -d '.' -f2)"
          echo "b64_token:"
          echo "$b64_token"

          decoded_token="$(echo $b64_token | base64 -d)"
          echo "decoded_token:"
          echo "$decoded_token"

          audience=$(echo "$decoded_token" | jq -r '.builder.audience')
          runner_label=$(echo "$decoded_token" | jq -r '.builder."runner-label"')
          private_repository=$(echo "$decoded_token" | jq -r '.builder."private-repository"')
          action_path=$(echo "$decoded_token" | jq -r '.tool.actions."build-artifacts".path')
          inputs=$(echo "$decoded_token" | jq -rc '.tool.inputs')
          run_attempt=$(echo "$decoded_token" | jq -r '.github.run_attempt')
          run_id=$(echo "$decoded_token" | jq -r '.github.run_id')
          run_number=$(echo "$decoded_token" | jq -r '.github.run_number')
          sha=$(echo "$decoded_token" | jq -r '.github.sha')
          workflow=$(echo "$decoded_token" | jq -r '.github.workflow')

          echo "audience: $audience"
          echo "runner_label: $runner_label"
          echo "private_repository: $private_repository"
          echo "action_path: $action_path"
          echo "inputs: $inputs"
          echo "run_attempt: $run_attempt - $GITHUB_RUN_ATTEMPT"
          echo "run_id: $run_id - $GITHUB_RUN_ID"
          echo "run_number: $run_number - $GITHUB_RUN_NUMBER"
          echo "sha: $sha - $GITHUB_SHA"
          echo "workflow: $workflow - $GITHUB_WORKFLOW"

          echo '0'
          [[ "$audience" == "delegator_generic_slsa3.yml" ]]
          echo '1'
          [[ "$run_attempt" == "$GITHUB_RUN_ATTEMPT" ]]
          echo '2'
          [[ "$run_number" == "$GITHUB_RUN_NUMBER" ]]
          echo '3'
          [[ "$run_id" == "$GITHUB_RUN_ID" ]]
          echo '4'
          [[ "$sha" == "$GITHUB_SHA" ]]
          echo '5'
          [[ "$workflow" == "$GITHUB_WORKFLOW" ]]
          echo '6'
          [[ "$runner_label" == "ubuntu-latest" ]]
          echo '7'
          [[ "$private_repository" == "true" ]]
          echo '8'
          [[ "$action_path" == "./actions/build-artifacts-composite" ]]
          echo '9'
          [[ "$inputs" == '{"name1":"value1","name2":"value2","private-repository":true}' ]]
          echo '10'
