name: Test Generate Attestation

on: 
  - workflow_dispatch

jobs:
  test_generate_attestation:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Create test inputs
        run: |
          cat <<EOF >DATA
          {
            "version": 1,
            "attestation1.intoto.json":[
              {
              "name": "artifact11",
              "digest": "abcde"
              },
              {
              "name": "artifact12",
              "digest": "iuyreq"
              }
            ],
            "attestation2.intoto.json":[
              {
              "name": "artifact21",
              "digest": "abcde"
              },
              {
              "name": "artifact22",
              "digest": "iuyreq"
              }
            ]
          }
          EOF
          cat DATA > slsa-outputs.json

          cat <<EOF >INPUTS
          {
            "release-tag": "v100"
            "private-repository": "true"
          }
          EOF
          INPUTS=$(cat INPUTS)
          echo "tool-inputs=${INPUTS}" >> $GITHUB_ENV

      - name: Test generate attestations
        id: sign
        uses: laurentsimon/slsa-delegator/.github/actions/internal/generate-attestations@main
        with:
          slsa-outputs-file: slsa-outputs.json
          tool-inputs: ${{ env.tool-inputs }}
          tool-uri: "https://github.com/laurentsimon/slsa-delegated-tool/.github/workflows/tool1_slsa3.yml@refs/heads/main"
          tool-path: "./actions/build-artifacts-composite"


